name: Docker Build and Deploy

on:
  push:
    branches:
      - lab1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Stop and remove existing container
        run: |
          sudo docker stop group3 || true
          sudo docker rm group3 || true

      - name: Build the Docker image
        run: |
          sudo docker build -t group3 .

      - name: Run the Docker container
        run: |
          sudo docker run -d --name group3 -p 80:80 group3
